const productVivo = [
    {
        details: 'OPPO A18 (Glowing Black, 128 GB)',
        rating:'4.2867 Ratings & 113 Reviews',
        memory:'8 GB RAM | 256 GB ROM',
        display:'16.64 cm (6.55 inch) Display',
        cameraQuality: '50MP Rear Camera | 32MP + 32MP Dual Front Camera',
        bettery:' 4700 mAh Battery',
        generation:'8s Gen 3 Mobile Platform Processor',
        warranty: '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
        img:'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/u/x/x/-original-imaguy4ag7rbpshw.jpeg?q=70',
        price:'9,999',
        dicountoff:'999',
        discountpersent:'25%',
        exchange:'4,590',   
    },
    {
        details: 'OPPO A18 (Glowing Black, 128 GB)',
        rating:'4.2867 Ratings & 113 Reviews',
        memory:'8 GB RAM | 256 GB ROM',
        display:'16.64 cm (6.55 inch) Display',
        cameraQuality: '50MP Rear Camera | 32MP + 32MP Dual Front Camera',
        bettery:' 4700 mAh Battery',
        generation:'8s Gen 3 Mobile Platform Processor',
        warranty: '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
        img:'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/b/m/e/-original-imaguy4b7uchxevz.jpeg?q=70',
        price:'9,999',
        dicountoff:'999',
        discountpersent:'25%',
        exchange:'4,590',   
    },
    {
        details: 'OPPO A18 (Glowing Black, 128 GB)',
        rating:'4.2867 Ratings & 113 Reviews',
        memory:'8 GB RAM | 256 GB ROM',
        display:'16.64 cm (6.55 inch) Display',
        cameraQuality: '50MP Rear Camera | 32MP + 32MP Dual Front Camera',
        bettery:' 4700 mAh Battery',
        generation:'8s Gen 3 Mobile Platform Processor',
        warranty: '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
        img:'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/u/x/x/-original-imaguy4ag7rbpshw.jpeg?q=70',
        price:'9,999',
        dicountoff:'999',
        discountpersent:'25%',
        exchange:'4,590',  
    },
    {
        details: 'OPPO A18 (Glowing Black, 128 GB)',
        rating:'4.2867 Ratings & 113 Reviews',
        memory:'8 GB RAM | 256 GB ROM',
        display:'16.64 cm (6.55 inch) Display',
        cameraQuality: '50MP Rear Camera | 32MP + 32MP Dual Front Camera',
        bettery:' 4700 mAh Battery',
        generation:'8s Gen 3 Mobile Platform Processor',
        warranty: '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
        img:'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/c/y/-original-imah57jbfqsz6797.jpeg?q=70',
        price:'9,999',
        dicountoff:'999',
        discountpersent:'25%',
        exchange:'4,590',   
    },
    {
        details: 'OPPO A18 (Glowing Black, 128 GB)',
        rating:'4.2867 Ratings & 113 Reviews',
        memory:'8 GB RAM | 256 GB ROM',
        display:'16.64 cm (6.55 inch) Display',
        cameraQuality: '50MP Rear Camera | 32MP + 32MP Dual Front Camera',
        bettery:' 4700 mAh Battery',
        generation:'8s Gen 3 Mobile Platform Processor',
        warranty: '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
        img:'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/c/y/-original-imah57jbfqsz6797.jpeg?q=70',
        price:'9,999',
        dicountoff:'999',
        discountpersent:'25%',
        exchange:'4,590',   
    },
    {
        details: 'OPPO A18 (Glowing Black, 128 GB)',
        rating:'4.2867 Ratings & 113 Reviews',
        memory:'8 GB RAM | 256 GB ROM',
        display:'16.64 cm (6.55 inch) Display',
        cameraQuality: '50MP Rear Camera | 32MP + 32MP Dual Front Camera',
        bettery:' 4700 mAh Battery',
        generation:'8s Gen 3 Mobile Platform Processor',
        warranty: '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
        img:'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/c/y/-original-imah57jbfqsz6797.jpeg?q=70',
        price:'9,999',
        dicountoff:'999',
        discountpersent:'25%',
        exchange:'4,590',   
    },
]

export default productVivo