'use client'
import "./globals.css";
// import Footer from "./Footer";
import { Toaster } from "react-hot-toast";
import { AppProvider } from "@/context/appContext";
// import Navbar from "./user/navbar";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// } 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          {/* <Navbar /> */}
          <Toaster position="top-right" />
          {children}
          {/* <Footer /> */}
        </AppProvider>
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
      </body>
    </html>
  )
}
