 const phoneData = [
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61fkOHNmzpL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61rnCkrurxL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/519FY4mW5oL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71Gu1ib5-RL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61EF7HnrWqL._AC_UL480_QL65_.jpg',
    }
 ];

 export default phoneData