const camara = [
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/617W4RHhxyL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71Cycmv-QCL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/612lOJ8eUqL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/51m5yrLxIyL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/41NUSIIp4LL._AC_UL480_FMwebp_QL65_.jpg',
    },
]

export default camara