const phones = [
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        save:'Save $0',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71XNeka-BRL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'8999',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        save:'Save $50',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'8999',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        save:'Save $50',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'8999',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        save:'Save $50',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71XNeka-BRL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'8999',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        save:'Save $50',
        img:'https://m.media-amazon.com/images/I/71XNeka-BRL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'899',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        img:'https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'8999',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        save:'Save $50',
        img:'https://m.media-amazon.com/images/I/71XNeka-BRL._AC_UL480_QL65_.jpg',
    },
    {
        details: 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android',
        festiwal:'Great Indian Festival',
        price:'8999',
        discount:'1200',
        percentOff: '(67% off)',
        lastDate:' Get it by Sunday 6 October',
        delivery:'FREE Delivery by Amazon',
        button: 'Add to cart',
        save:'Save $50',
        img:'https://m.media-amazon.com/images/I/71XNeka-BRL._AC_UL480_QL65_.jpg',
    },
];

export default phones