'use client'
// import "./globals.css";
import Footer from "./footer";
import { Toaster } from "react-hot-toast";
// import { AppProvider } from "@/context/appContext";
import Navbar from "./navbar";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// } 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <AppProvider> */}
          <Navbar />
          <Toaster position="top-right" />
          {children}
          <Footer />
        {/* </AppProvider> */}
      </body>
    </html>
  )
}
